export const USER_AUTHENTICATE = 'USER/AUTHENTICATE';
export const USER_CHECK_LOGIN = 'USER/CHECK_LOGIN';
export const USER_LOGOUT = 'USER/LOGOUT';
export const USER_SET = 'USER/SET';

export const HOTELS_GET = 'HOTELS/GET';
export const HOTELS_SET = 'HOTELS/SET';

export const FAVORITES_SET = 'FAVORITES/SET';
export const FAVORITES_TOGGLE = 'FAVORITES/TOGGLE';
